-- message table
CREATE TABLE IF NOT EXISTS MESSAGES (MESSAGE TEXT NOT NULL, MESSAGEID INTEGER  PRIMARY KEY AUTOINCREMENT);

INSERT INTO MESSAGES
    (MESSAGE) 
VALUES
("君なら大丈夫！"),
("お腹いっぱいなので寝ます"),
("ささみがうまいんだよなぁ"),
("元気だして！"),
("仰向けで股広げて寝てます"),
("他人と比べるんじゃなくて過去の自分と比べよう！");

-- replies table
CREATE TABLE IF NOT EXISTS REPLIES (TARGET_WORD TEXT NOT NULL, REPLY_WORD TEXT NOT NULL,REPLYID INTEGER  PRIMARY KEY AUTOINCREMENT);
INSERT INTO REPLIES
    (TARGET_WORD, REPLY_WORD)
VALUES
("ただいま", "おかえり！"),
("疲れた","お疲れ様! よく頑張ったね！");


CREATE TABLE IF NOT EXISTS USERS (DIALY_MODE_FLAG INTEGER NOT NULL, USERID TEXT PRIMARY KEY);
